language: php
sudo: required
dist: trusty
services:
  - mysql
php:
    - 5.6
#    - 7.0
addons:
  hosts:
    - magento-2-travis.dev
before_script:
    # get latest composer and disable xdebug for perf    
    - composer selfupdate
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini   
    # add multiverse, update apt
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse" && sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
    - sudo apt-get update -qq 
    # add mysql 5.6
    - sudo apt-get remove -y -qq --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5
    - sudo apt-get -y -qq autoremove;
    - sudo apt-get -y -qq autoclean;
    - sudo apt-get install -y -qq mysql-server-5.6 mysql-client-5.6;    
    - mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE magento_2_travis;';
    # add apache
    - sudo apt-get install -y -qq apache2 libapache2-mod-fastcgi
    #   enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    #   configure apache virtual hosts
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    - sudo service apache2 restart  
    - sudo ls /etc/apache2/sites-available
    - sudo ls /etc/apache2/sites-enabled
    - pwd
    # awful hack using during travis debugging that I swear I'm going to remove
    # but then again you're reading this so I didn't remove it and **sigh**
    - sudo find .. -exec chmod 777 '{}' +
    - sudo find /var/log/apache -exec cat '{}' \;
#         
#    # clone main magento github repository
#    - git clone https://github.com/magento/magento2
#    # use sed to insert astorm/pulsestorm into magento's composer.json
#    # wrapped in a build script because travis yaml parsing
#    - ./build.sh
#    # download latest pestle phar
#    - curl -LO http://pestle.pulsestorm.net/pestle.phar        
#    # install Magento
#    - cd magento2        
#    - composer update    
#    - php bin/magento setup:install --admin-email astorm@alanstorm.com --admin-firstname Alan --admin-lastname Storm --admin-password ih8magento --admin-user astorm --backend-frontname admin --base-url http://magento-2-travis.dev --db-host 127.0.0.1 --db-name magento_2_travis --db-user root --session-save files --use-rewrites 1 --use-secure 0 -vvv
    - curl http://magento-2-travis.dev/index.php
    - curl http://magento-2-travis.dev/    
script: vendor/bin/phpunit vendor/pulsestorm/pestle/tests-integration/FirstTest.php 
