language: php
services:
  - mysql
php:
    - 5.6
    - 7.0
before_script:
    - git clone https://github.com/magento/magento2
    - ./build.sh
    - curl -LO http://pestle.pulsestorm.net/pestle.phar    
    - cd magento2    
    - cat composer.json
    - composer selfupdate
    - composer update
    - mysql -e 'create database magento_2_travis;'
    - php bin/magento setup:install --admin-email astorm@alanstorm.com --admin-firstname Alan --admin-lastname Storm --admin-password ih8magento --admin-user astorm --backend-frontname admin --base-url http://magento-2-travis.dev --db-host 127.0.0.1 --db-name magento_2_travis --db-user root --session-save files --use-rewrites 1 --use-secure 0 -vvv
script: vendor/bin/phpunit vendor/pulsestorm/pestle/tests-integration/FirstTest.php 
