language: php
services:
  - mysql
php:
    - 5.6
    - 7.0
before_script:
    - git clone https://github.com/magento/magento2
    - cd magento2
    - ../build.sh
script: vendor/bin/phpunit vendor/pulsestorm/pestle/tests-integration/FirstTest.php 
