language: php
services:
  - mysql
php:
    - 5.6
    - 7.0
before_script:
    - git clone git@github.com:magento/magento2.git
    - cd magento2
    - "sed 's/\(\"require\": {\)/\1\"pulsestorm\/pestle\":\"dev-master\",/' composer.json"
    - composer install
    - curl -LO http://pestle.pulsestorm.net/pestle.phar
    
script: vendor/bin/phpunit vendor/pulsestorm/pestle/tests-integration/FirstTest.php 
