env:
    global:
    - PULSESTORM_MAGE2_FAKE_URL=http://magento-2-travis.dev
    - PULSESTORM_MAGE2_ADMIN_EMAIL=astorm@alanstorm.com
    - PULSESTORM_MAGE2_ADMIN_FIRST_NAME=Alan    
    - PULSESTORM_MAGE2_ADMIN_LAST_NAME=Storm
    - PULSESTORM_MAGE2_ADMIN_USERNAME=astorm            
    - PULSESTORM_MAGE2_ADMIN_PASSWORD=ih3artmagento            
    - PULSESTORM_MAGE2_ADMIN_DBNAME=magento_2_travis                
    - PULSESTORM_PESTLE_URL=http://pestle.pulsestorm.net    
language: php
sudo: required
dist: trusty
php:
    - 5.6
addons:
  hosts:
    - magento-2-travis.dev
before_script:
    # some useful debugging stuff for travis
    #- curl http://magento-2-travis.dev/index.php
    #- curl http://magento-2-travis.dev/  
    #- sudo find /var/log/apache2 -exec cat '{}' \;      
    #- sudo cat /etc/apache2/sites-available/000-default.conf
    #- sudo cat /etc/apache2/sites-enabled/000-default.conf    
    #- sudo apachectl -V
    #- sudo apache2ctl -V
    #- ls -lh $TRAVIS_BUILD_DIR
    #- sudo ls /etc/apache2/sites-available
    #- sudo ls /etc/apache2/sites-enabled
    #- pwd    
    #    
    # get latest composer and disable xdebug for perf    
    - composer selfupdate
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini   
    # add multiverse, update apt
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse" && sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
    - sudo apt-get update -qq 
    # add mysql 5.6
    - sudo apt-get remove -y -qq --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5
    - sudo apt-get -y -qq autoremove;
    - sudo apt-get -y -qq autoclean;
    - sudo apt-get install -y -qq mysql-server-5.6 mysql-client-5.6;    
    - mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE magento_2_travis;';
    # add apache
    - sudo apt-get install -y -qq apache2 libapache2-mod-fastcgi
    #   enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    #   awful hack used during travis debugging that I swear I'm going to remove
    #   but then again you're reading this so I didn't remove it and **sigh**    
    - sudo chmod 777 /home /home/travis /home/travis/build            

    #   configure apache virtual hosts
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    - sudo service apache2 restart 

    # clone main magento github repository
    - git clone https://github.com/magento/magento2
    # download latest pestle phar and install
    - curl -LO "$PULSESTORM_PESTLE_URL/pestle.phar"
    - sudo mv pestle.phar /usr/local/bin
    - sudo chmod +x /usr/local/bin/pestle.phar
    # use build.sh script to add pestle repository to composer.json
    #- ./build.sh        
    - php addRepositoryToComposer.php composer.json > composer.json
    # install Magento
    - cd magento2  
    # add pestle project to get tests
    - composer require pulsestorm/pestle dev-master          
    #- composer update    
    #- php bin/magento setup:install --admin-email astorm@alanstorm.com --admin-firstname Alan --admin-lastname Storm --admin-password ih8magento --admin-user astorm --backend-frontname admin --base-url "$PULSESTORM_MAGE2_FAKE_URL" --db-host 127.0.0.1 --db-name magento_2_travis --db-user root --session-save files --use-rewrites 1 --use-secure 0 -vvv
    - php bin/magento setup:install --admin-email "$PULSESTORM_MAGE2_ADMIN_EMAIL" --admin-firstname "$PULSESTORM_MAGE2_ADMIN_FIRST_NAME" --admin-lastname "$PULSESTORM_MAGE2_ADMIN_LAST_NAME" --admin-password "$PULSESTORM_MAGE2_ADMIN_PASSWORD" --admin-user "$PULSESTORM_MAGE2_ADMIN_USERNAME" --backend-frontname admin --base-url "$PULSESTORM_MAGE2_FAKE_URL" --db-host 127.0.0.1 --db-name magento_2_travis --db-user root --session-save files --use-rewrites 1 --use-secure 0 -vvv    
    # test that magento is installed
    - curl "$PULSESTORM_MAGE2_FAKE_URL/index.php"
    - pestle.phar hello_world
script: vendor/bin/phpunit vendor/pulsestorm/pestle/tests-integration/FirstTest.php 
